export const PAGE_TYPES = [
  [
    "landing",
    "落地页",
    "bi-window-stack",
    "品牌表达与转化路径",
    "产品落地页：首屏 Hero、卖点分区、客户证言、定价表与页脚",
  ],
  [
    "dashboard",
    "仪表盘",
    "bi-speedometer2",
    "指标监控与数据概览",
    "数据仪表盘：侧边导航、KPI 指标卡、趋势图表与明细数据表格",
  ],
  [
    "ecommerce",
    "电商页面",
    "bi-bag",
    "商品展示与购买转化",
    "电商页面：商品主图、价格与规格选择、购买按钮、评价与推荐位",
  ],
  [
    "feed",
    "信息流",
    "bi-view-list",
    "内容发现与持续浏览",
    "信息流页面：顶部导航、内容卡片流、互动按钮与底部标签栏",
  ],
  [
    "auth",
    "登录注册",
    "bi-person-lock",
    "账号验证与身份进入",
    "登录/注册页：品牌展示区、表单、第三方登录与协议说明",
  ],
  [
    "settings",
    "设置页",
    "bi-sliders2",
    "偏好配置与账户管理",
    "设置页面：分组设置列表、开关与输入控件、账号与危险操作区",
  ],
  [
    "profile",
    "个人中心",
    "bi-person-circle",
    "资料、数据与个人入口",
    "个人中心页：头像资料卡、数据统计、功能入口列表",
  ],
  [
    "chat",
    "聊天对话",
    "bi-chat-dots",
    "会话协作与即时沟通",
    "即时通讯界面：会话列表、消息气泡、输入框与工具栏",
  ],
  [
    "onboarding",
    "引导页",
    "bi-signpost-split",
    "新用户认知与步骤引导",
    "新用户引导页：主题插画、步骤指示器、行动按钮",
  ],
  [
    "workspace",
    "工作台",
    "bi-columns-gap",
    "多任务生产与快捷操作",
    "业务工作台：全局导航、快捷操作区、待办任务、最近项目与动态记录",
  ],
  [
    "crm",
    "客户管理",
    "bi-person-lines-fill",
    "线索、客户与跟进流程",
    "CRM 客户管理页：客户列表、阶段漏斗、负责人、跟进记录与批量操作",
  ],
  [
    "analytics",
    "数据分析",
    "bi-graph-up-arrow",
    "多维筛选与趋势洞察",
    "数据分析页：时间与维度筛选、核心趋势图、对比指标、明细表和洞察摘要",
  ],
  [
    "admin",
    "管理后台",
    "bi-layout-sidebar-inset",
    "高密度运营与权限操作",
    "管理后台：稳定侧边导航、筛选工具栏、数据表格、状态标签与批量操作",
  ],
  [
    "finance",
    "金融账务",
    "bi-wallet2",
    "资产、账单与交易明细",
    "金融账务页：资产概览、收支趋势、账户卡片、交易流水与风险提示",
  ],
  [
    "education",
    "在线教育",
    "bi-mortarboard",
    "课程学习与进度管理",
    "在线教育页：课程目录、学习进度、视频区域、章节任务、笔记与讨论区",
  ],
  [
    "healthcare",
    "医疗健康",
    "bi-heart-pulse",
    "健康数据与服务预约",
    "医疗健康页：健康概览、指标趋势、服务入口、预约信息与风险提醒",
  ],
  [
    "booking",
    "预订服务",
    "bi-calendar2-check",
    "时间、资源与订单确认",
    "预订服务页：搜索条件、日期与时段选择、资源列表、价格明细和订单确认",
  ],
  [
    "media",
    "媒体播放",
    "bi-play-btn",
    "影音浏览与播放控制",
    "媒体播放页：内容主视觉、播放器、频道分类、推荐列表、收藏与播放队列",
  ],
  [
    "portfolio",
    "作品集",
    "bi-grid-1x2",
    "项目展示与个人表达",
    "作品集页面：个人或团队介绍、精选项目、案例详情入口、能力标签与联系方式",
  ],
  ["custom", "自定义", "bi-pencil-square", "自由定义页面信息结构", ""],
].map(([id, label, icon, description, prompt]) => ({
  id,
  label,
  icon,
  description,
  prompt,
}));

export const VISUAL_STYLES = [
  [
    "minimal",
    "极简留白",
    "bi-layout-text-sidebar-reverse",
    "克制、清晰、重视内容",
    ["#f7f7f8", "#18181b", "#e4e4e7"],
    "极简主义：大量留白、克制配色、精致排版",
  ],
  [
    "glass",
    "玻璃拟态",
    "bi-layers",
    "半透明层次与柔和光感",
    ["#1d1830", "#9f8cff", "#493d68"],
    "玻璃拟态：半透明磨砂卡片、柔和渐变背景、细腻高光",
  ],
  [
    "darkpro",
    "深色专业",
    "bi-moon-stars",
    "高对比、沉稳、专业工具感",
    ["#111318", "#e5e7eb", "#343946"],
    "深色专业：深灰背景、高对比信息层级、克制的强调色",
  ],
  [
    "vibrant",
    "多彩活力",
    "bi-palette",
    "明快色彩与活泼节奏",
    ["#ff5a67", "#6558f5", "#ffc857"],
    "多彩活力：明快配色、大圆角、活泼插画点缀",
  ],
  [
    "corporate",
    "商务企业",
    "bi-buildings",
    "稳重、可信、结构严谨",
    ["#16324f", "#2f81f7", "#dbe8f5"],
    "商务企业：稳重蓝灰配色、清晰栅格、正式可信",
  ],
  [
    "neubrutal",
    "新粗野",
    "bi-bounding-box",
    "硬边界、强对比、个性直接",
    ["#f8ef52", "#ff6b6b", "#111111"],
    "新粗野主义：粗描边、硬阴影、高饱和撞色色块",
  ],
  [
    "editorial",
    "杂志编辑",
    "bi-newspaper",
    "大标题、强节奏、内容叙事",
    ["#f3f0ea", "#171717", "#b5342b"],
    "杂志编辑风格：鲜明版式节奏、精致大标题、图文比例讲究且内容导向明确",
  ],
  [
    "luxury",
    "高端奢华",
    "bi-gem",
    "精致、稀缺、克制质感",
    ["#171512", "#d8c28f", "#f4f0e8"],
    "高端奢华风格：精致材质感、克制高光、宽松排版和高品质视觉细节",
  ],
  [
    "friendly",
    "亲和圆润",
    "bi-emoji-smile",
    "柔和、易用、具有温度",
    ["#fff7ed", "#34a37b", "#ff8a65"],
    "亲和圆润风格：柔和形态、自然配色、清晰反馈，友好但不过度幼态",
  ],
  [
    "futuristic",
    "未来科技",
    "bi-cpu",
    "精密、前沿、数字空间感",
    ["#080b12", "#31e6c2", "#5965ff"],
    "未来科技风格：精密网格、冷色高亮、数据化细节和克制的数字空间感",
  ],
  [
    "organic",
    "自然有机",
    "bi-flower1",
    "自然色彩与柔和秩序",
    ["#edf3ea", "#3f7552", "#d59b67"],
    "自然有机风格：自然色彩、柔和边缘、舒缓层级与真实材质图片",
  ],
  [
    "monochrome",
    "黑白单色",
    "bi-circle-half",
    "纯粹、高级、强调排版",
    ["#ffffff", "#111111", "#a1a1aa"],
    "黑白单色风格：主要使用黑白灰，通过字号、字重、留白和边界建立层级",
  ],
].map(([id, label, icon, description, preview, prompt]) => ({
  id,
  label,
  icon,
  description,
  preview,
  prompt,
}));

export const BRAND_COLORS = [
  ["#6d5cff", "星云紫", "创意与智能产品"],
  ["#2f81f7", "科技蓝", "科技与效率工具"],
  ["#12b76a", "活力绿", "增长与健康服务"],
  ["#f79009", "暖阳橙", "消费与生活方式"],
  ["#f04438", "珊瑚红", "行动与重要提醒"],
  ["#d444f1", "霓虹紫", "潮流与娱乐平台"],
  ["#0e9384", "青碧绿", "专业与可持续"],
  ["#334155", "石墨蓝", "企业与数据产品"],
  ["#e5484d", "朱砂红", "品牌与内容传播"],
  ["#7c3aed", "电光紫", "数字内容与社区"],
  ["#0891b2", "湖水青", "服务与信息平台"],
  ["#18181b", "经典黑", "高端与极简品牌"],
].map(([value, label, description]) => ({ value, label, description }));

export const SPEC_OPTIONS = {
  audience: [
    ["consumer", "大众用户"],
    ["professional", "专业用户"],
    ["enterprise", "企业团队"],
  ],
  goal: [
    ["conversion", "转化"],
    ["workflow", "任务效率"],
    ["content", "内容浏览"],
    ["insight", "数据洞察"],
  ],
  navigation: [
    ["auto", "智能布局"],
    ["top", "顶部导航"],
    ["sidebar", "侧边导航"],
    ["hybrid", "混合导航"],
    ["bottom", "底部标签栏"],
  ],
  density: [
    ["compact", "紧凑"],
    ["balanced", "均衡"],
    ["comfortable", "宽松"],
  ],
  typography: [
    ["neutral", "中性无衬线"],
    ["technical", "技术理性"],
    ["editorial", "编辑感"],
    ["friendly", "亲和圆润"],
  ],
  radius: [
    ["sharp", "硬朗 4px"],
    ["medium", "标准 8px"],
    ["soft", "柔和 12px"],
  ],
  responsive: [
    ["adaptive", "自适应"],
    ["desktop-first", "桌面优先"],
  ],
};

export const COMPONENT_STATES = [
  ["interaction", "交互"],
  ["loading", "加载"],
  ["empty", "空状态"],
  ["error", "错误"],
  ["disabled", "禁用"],
  ["success", "成功"],
].map(([id, label]) => ({ id, label }));
