/**
 * 全屏预览滤镜预设：面向壁纸场景，少做噱头，多做稳定、可预期的调色。
 */

export const FILTER_PRESET_GROUPS = [
  { id: 'base', label: '经典基础' },
  { id: 'film', label: '胶片复古' },
  { id: 'cinema', label: '电影氛围' },
  { id: 'portrait', label: '人像美颜' },
  { id: 'korean', label: '韩系滤镜' },
  { id: 'japanese', label: '日系滤镜' },
  { id: 'social', label: 'INS/小红书' },
  { id: 'camera', label: '相机色彩' },
  { id: 'mono', label: '黑白' },
  { id: 'dream', label: '梦幻' },
  { id: 'nature', label: '自然风景' },
  { id: 'night', label: '夜景城市' },
  { id: 'future', label: '科技未来' },
  { id: 'custom', label: '我的预设' },
]

const DEFAULT_PARAMS = {
  brightness: 100,
  contrast: 100,
  saturation: 100,
  blur: 0,
  grayscale: 0,
  sepia: 0,
  hueRotate: 0,
  invert: 0,
  temperature: 0,
  tint: 0,
  fade: 0,
  shadowCool: 0,
  highlightWarm: 0,
  vignette: 0,
  lutStyle: 'none',
  lutIntensity: 0,
  curveStrength: 0,
  grain: 0,
  skinProtect: 70,
  exposure: 0,
  highlights: 0,
  shadows: 0,
  blackPoint: 0,
  vibrance: 0,
  clarity: 0,
  skinSmooth: 0,
  skinWarmth: 0,
  cameraProfile: 'none',
  profileIntensity: 0,
}

function preset(id, label, group, description, filterParams) {
  return {
    id,
    label,
    group,
    description,
    activeFilter: id === 'none' ? 'none' : 'custom',
    filterIntensity: 100,
    filterParams: { ...DEFAULT_PARAMS, ...(filterParams || {}) },
  }
}

function portraitParams(params) {
  return {
    skinProtect: 92,
    skinSmooth: 12,
    saturation: 96,
    contrast: 98,
    ...params,
  }
}

function filmParams(params) {
  return {
    grain: 8,
    fade: 8,
    ...params,
  }
}

function nightParams(params) {
  return {
    shadowCool: 14,
    vignette: 12,
    ...params,
  }
}

function cameraParams(profile, params) {
  return {
    cameraProfile: profile,
    profileIntensity: 55,
    ...params,
  }
}

export const FILTER_PRESETS = [
  preset('none', '原图', 'base', '不应用任何风格'),
  preset('auto_enhance', '自动增强', 'base', '轻微提亮、增强层次', {
    brightness: 103,
    contrast: 110,
    saturation: 106,
    lutStyle: 'clean',
    lutIntensity: 24,
    curveStrength: 8,
  }),
  preset('natural', '自然', 'base', '保持原图气质，只做轻微优化', {
    brightness: 102,
    contrast: 104,
    saturation: 102,
    lutStyle: 'clean',
    lutIntensity: 12,
    skinProtect: 84,
  }),
  preset('fresh', '清新', 'base', '更明亮、更轻盈', {
    brightness: 106,
    contrast: 101,
    saturation: 108,
    temperature: -4,
    lutStyle: 'clean',
    lutIntensity: 28,
    curveStrength: -4,
  }),
  preset('bright_clear', '通透', 'base', '提升明度和透明感', {
    brightness: 108,
    contrast: 112,
    saturation: 104,
    shadowCool: 5,
    lutStyle: 'clean',
    lutIntensity: 34,
    curveStrength: 10,
  }),
  preset('vivid', '鲜艳', 'base', '颜色更饱满，适合插画和风景', {
    brightness: 102,
    contrast: 108,
    saturation: 116,
    lutStyle: 'clean',
    lutIntensity: 18,
    curveStrength: 6,
  }),
  preset('balanced', '平衡', 'base', '中性调整，适合作为起点', {
    brightness: 101,
    contrast: 106,
    saturation: 100,
  }),
  preset('hd_clear', '高清', 'base', '增强对比和细节感', {
    brightness: 102,
    contrast: 122,
    saturation: 108,
  }),
  preset('soft_focus', '柔焦', 'base', '轻微柔化画面', {
    brightness: 104,
    contrast: 96,
    saturation: 102,
    blur: 0.55,
    fade: 6,
    lutStyle: 'dream',
    lutIntensity: 18,
    skinProtect: 88,
  }),
  preset('cool_tone', '冷调', 'base', '偏冷、清爽、克制', {
    brightness: 101,
    contrast: 104,
    saturation: 94,
    temperature: -12,
    shadowCool: 10,
    lutStyle: 'clean',
    lutIntensity: 18,
  }),
  preset('warm_sun', '暖阳', 'base', '自然暖光，不重口', {
    brightness: 104,
    contrast: 102,
    saturation: 104,
    sepia: 4,
    temperature: 10,
    highlightWarm: 12,
    lutStyle: 'film_gold',
    lutIntensity: 20,
    skinProtect: 86,
  }),

  preset('kodak_gold', '柯达金', 'film', '温暖、饱满、偏日常胶片', filmParams({
    brightness: 103,
    contrast: 106,
    saturation: 108,
    sepia: 8,
    temperature: 12,
    highlightWarm: 16,
    lutStyle: 'film_gold',
    lutIntensity: 64,
    curveStrength: 6,
    skinProtect: 82,
  })),
  preset('kodak_portra', '柯达人像', 'film', '柔和肤色、低反差人像胶片', filmParams({
    brightness: 104,
    contrast: 96,
    saturation: 96,
    sepia: 5,
    temperature: 8,
    highlightWarm: 10,
    lutStyle: 'kodak_portra',
    lutIntensity: 70,
    curveStrength: -8,
    grain: 6,
    skinProtect: 90,
  })),
  preset('fuji_classic', '富士经典', 'film', '低饱和、柔和绿色倾向', filmParams({
    brightness: 101,
    contrast: 104,
    saturation: 88,
    sepia: 4,
    temperature: -6,
    fade: 5,
    lutStyle: 'fuji_classic',
    lutIntensity: 58,
    curveStrength: -4,
    grain: 7,
  })),
  preset('fuji_vivid', '富士鲜艳', 'film', '更鲜明的绿色和蓝色', {
    brightness: 101,
    contrast: 112,
    saturation: 114,
    temperature: -4,
    lutStyle: 'fuji_vivid',
    lutIntensity: 64,
    curveStrength: 12,
    grain: 4,
    skinProtect: 78,
  }),
  preset('cinestill_800t', '电影胶卷', 'film', '钨丝灯夜景胶片感', {
    brightness: 96,
    contrast: 112,
    saturation: 110,
    temperature: -10,
    tint: 8,
    shadowCool: 14,
    highlightWarm: 18,
    vignette: 12,
    lutStyle: 'cinestill',
    lutIntensity: 72,
    curveStrength: 8,
    grain: 12,
    skinProtect: 78,
  }),
  preset('retro_film', '复古胶片', 'film', '轻微褪色与暖调', {
    brightness: 101,
    contrast: 96,
    saturation: 88,
    blur: 0.25,
    sepia: 10,
    temperature: 8,
    fade: 16,
    lutStyle: 'film_matte',
    lutIntensity: 70,
    curveStrength: -10,
    grain: 14,
  }),
  preset('old_photo', '老照片', 'film', '偏旧照的褐色记忆', {
    brightness: 97,
    contrast: 92,
    saturation: 74,
    sepia: 26,
    temperature: 16,
    fade: 18,
    lutStyle: 'film_gold',
    lutIntensity: 58,
    curveStrength: -14,
    grain: 18,
  }),
  preset('matte_film', '哑光胶片', 'film', '低对比、柔和暗部', {
    brightness: 104,
    contrast: 88,
    saturation: 90,
    sepia: 10,
    fade: 22,
    lutStyle: 'film_matte',
    lutIntensity: 74,
    curveStrength: -18,
    grain: 10,
  }),
  preset('silver_salt', '银盐', 'film', '黑白胶片质感', {
    brightness: 100,
    contrast: 118,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 36,
    curveStrength: 10,
    grain: 10,
  }),
  preset('time_mark', '时光印记', 'film', '微暖、低饱和、带旧感', {
    brightness: 98,
    contrast: 96,
    saturation: 82,
    sepia: 12,
    temperature: 8,
    fade: 14,
    lutStyle: 'film_matte',
    lutIntensity: 62,
    curveStrength: -8,
    grain: 12,
  }),

  preset('cinematic', '电影感', 'cinema', '压一点亮度，拉开层次', {
    brightness: 96,
    contrast: 120,
    saturation: 106,
    shadowCool: 12,
    vignette: 10,
    lutStyle: 'cinema',
    lutIntensity: 58,
    curveStrength: 16,
  }),
  preset('black_gold', '黑金电影', 'cinema', '暗部更深，暖色更突出', {
    brightness: 94,
    contrast: 124,
    saturation: 106,
    sepia: 8,
    temperature: 6,
    shadowCool: 10,
    highlightWarm: 22,
    vignette: 18,
    lutStyle: 'cinema',
    lutIntensity: 70,
    curveStrength: 18,
    skinProtect: 76,
  }),
  preset('commercial_blockbuster', '商业大片', 'cinema', '蓝色阴影与暖高光', {
    brightness: 95,
    contrast: 126,
    saturation: 108,
    temperature: -8,
    shadowCool: 20,
    highlightWarm: 18,
    vignette: 18,
    lutStyle: 'blockbuster',
    lutIntensity: 72,
    curveStrength: 18,
    skinProtect: 78,
  }),
  preset('teal_orange', '青橙电影', 'cinema', '克制的冷暖分离感', {
    brightness: 96,
    contrast: 112,
    saturation: 108,
    sepia: 4,
    temperature: -6,
    shadowCool: 18,
    highlightWarm: 12,
    lutStyle: 'cinema',
    lutIntensity: 66,
    curveStrength: 12,
    skinProtect: 78,
  }),
  preset('midnight_theater', '午夜剧场', 'cinema', '深色、冷调、夜间氛围', {
    brightness: 88,
    contrast: 124,
    saturation: 82,
    grayscale: 4,
    shadowCool: 22,
    vignette: 24,
    lutStyle: 'night',
    lutIntensity: 60,
    curveStrength: 14,
  }),
  preset('sci_fi_blue', '科幻蓝调', 'cinema', '偏蓝、清冷、硬朗', {
    brightness: 94,
    contrast: 118,
    saturation: 98,
    temperature: -14,
    shadowCool: 18,
    lutStyle: 'cyber',
    lutIntensity: 42,
    curveStrength: 10,
  }),
  preset('neon_night', '霓虹夜', 'cinema', '更高饱和的城市夜色', {
    brightness: 96,
    contrast: 118,
    saturation: 120,
    tint: 10,
    shadowCool: 18,
    vignette: 14,
    lutStyle: 'neon',
    lutIntensity: 70,
    curveStrength: 16,
  }),
  preset('drama_light', '光影戏剧', 'cinema', '强调明暗反差', {
    brightness: 95,
    contrast: 128,
    saturation: 96,
    shadowCool: 8,
    highlightWarm: 8,
    vignette: 20,
    lutStyle: 'cinema',
    lutIntensity: 52,
    curveStrength: 24,
  }),

  preset('portrait_soft_skin', '人像柔肤', 'portrait', '保留肤色的柔和人像', portraitParams({
    brightness: 104,
    contrast: 94,
    saturation: 95,
    blur: 0.12,
    fade: 6,
    lutStyle: 'kodak_portra',
    lutIntensity: 42,
    curveStrength: -8,
    skinProtect: 98,
  })),
  preset('natural_beauty', '自然美颜', 'portrait', '轻微提气色，不重口', portraitParams({
    brightness: 103,
    contrast: 99,
    saturation: 100,
    temperature: 3,
    highlightWarm: 6,
    lutStyle: 'kodak_portra',
    lutIntensity: 28,
    curveStrength: -2,
    skinProtect: 96,
  })),
  preset('oxygen_portrait', '氧气感', 'portrait', '轻亮、通透、肤色干净', portraitParams({
    brightness: 106,
    contrast: 96,
    saturation: 96,
    exposure: 6,
    highlights: -6,
    shadows: 8,
    skinSmooth: 14,
    skinWarmth: 2,
    lutStyle: 'japan_clear',
    lutIntensity: 28,
    curveStrength: -4,
    cameraProfile: 'canon_portrait',
    profileIntensity: 34,
    skinProtect: 98,
  })),
  preset('clean_nude_makeup', '清透裸妆', 'portrait', '低饱和、轻气色、裸妆感', portraitParams({
    brightness: 104,
    contrast: 94,
    saturation: 90,
    exposure: 4,
    highlights: -4,
    shadows: 6,
    skinSmooth: 16,
    skinWarmth: 4,
    lutStyle: 'kodak_portra',
    lutIntensity: 30,
    curveStrength: -6,
    cameraProfile: 'hasselblad_natural',
    profileIntensity: 32,
    skinProtect: 98,
  })),
  preset('cream_skin', '奶油肌', 'portrait', '奶油色高光和柔雾肤感', {
    brightness: 106,
    contrast: 90,
    saturation: 90,
    fade: 14,
    highlightWarm: 8,
    lutStyle: 'korean_cream',
    lutIntensity: 54,
    curveStrength: -12,
    skinProtect: 98,
  }),
  preset('backlight_portrait', '逆光人像', 'portrait', '抬高光、保留轮廓', {
    brightness: 104,
    contrast: 102,
    saturation: 96,
    temperature: 6,
    highlightWarm: 14,
    vignette: 8,
    lutStyle: 'kodak_portra',
    lutIntensity: 34,
    curveStrength: 4,
    skinProtect: 96,
  }),
  preset('studio_portrait', '棚拍光', 'portrait', '干净、清晰、肤色克制', {
    brightness: 102,
    contrast: 108,
    saturation: 94,
    highlights: -6,
    shadows: 4,
    clarity: 8,
    skinSmooth: 8,
    lutStyle: 'clean',
    lutIntensity: 28,
    curveStrength: 10,
    cameraProfile: 'sony_clean',
    profileIntensity: 36,
    skinProtect: 96,
  }),
  preset('star_portrait', '明星写真', 'portrait', '棚拍质感、柔肤和立体高光', portraitParams({
    brightness: 103,
    contrast: 104,
    saturation: 94,
    highlights: -8,
    shadows: 4,
    blackPoint: 2,
    clarity: 6,
    skinSmooth: 18,
    skinWarmth: 2,
    vignette: 4,
    lutStyle: 'kodak_portra',
    lutIntensity: 34,
    curveStrength: 6,
    cameraProfile: 'canon_portrait',
    profileIntensity: 44,
    skinProtect: 98,
  })),
  preset('mood_portrait', '氛围人像', 'portrait', '电影感阴影与柔和肤色', {
    brightness: 100,
    contrast: 104,
    saturation: 92,
    shadowCool: 8,
    highlightWarm: 6,
    vignette: 10,
    lutStyle: 'cinema',
    lutIntensity: 34,
    curveStrength: 4,
    skinProtect: 96,
  }),

  preset('seoul', '首尔', 'korean', '明亮、柔白、低饱和', {
    brightness: 106,
    contrast: 90,
    saturation: 88,
    fade: 12,
    lutStyle: 'korean_cream',
    lutIntensity: 54,
    curveStrength: -12,
    skinProtect: 98,
  }),
  preset('k_drama', '韩剧氛围', 'korean', '清透柔光和奶白高光', {
    brightness: 104,
    contrast: 94,
    saturation: 92,
    temperature: 3,
    fade: 10,
    lutStyle: 'korean_cream',
    lutIntensity: 48,
    curveStrength: -8,
    skinProtect: 96,
  }),
  preset('milk_white', '奶白', 'korean', '奶白低对比', {
    brightness: 108,
    contrast: 88,
    saturation: 84,
    fade: 14,
    lutStyle: 'korean_cream',
    lutIntensity: 52,
    curveStrength: -12,
    skinProtect: 98,
  }),
  preset('cafe_korea', '咖啡馆', 'korean', '咖啡色暖光和轻胶片', {
    brightness: 100,
    contrast: 94,
    saturation: 90,
    sepia: 6,
    temperature: 8,
    fade: 10,
    lutStyle: 'xiaohongshu_oat',
    lutIntensity: 42,
    curveStrength: -8,
    grain: 6,
    skinProtect: 92,
  }),
  preset('clean_white_tone', '纯净白调', 'korean', '干净、留白、柔亮', {
    brightness: 110,
    contrast: 94,
    saturation: 86,
    temperature: -1,
    fade: 12,
    lutStyle: 'clean',
    lutIntensity: 34,
    curveStrength: -10,
    skinProtect: 96,
  }),

  preset('tokyo', '东京', 'japanese', '城市日系清透', {
    brightness: 104,
    contrast: 100,
    saturation: 94,
    temperature: -3,
    lutStyle: 'japan_clear',
    lutIntensity: 44,
    curveStrength: -2,
    skinProtect: 92,
  }),
  preset('kyoto', '京都', 'japanese', '柔和暖色与低对比', {
    brightness: 104,
    contrast: 94,
    saturation: 90,
    sepia: 5,
    temperature: 8,
    fade: 10,
    lutStyle: 'film_matte',
    lutIntensity: 46,
    curveStrength: -8,
    grain: 5,
    skinProtect: 86,
  }),
  preset('sakura', '樱花', 'japanese', '淡粉高光和轻盈空气感', {
    brightness: 106,
    contrast: 92,
    saturation: 92,
    tint: 4,
    fade: 10,
    lutStyle: 'sakura',
    lutIntensity: 48,
    curveStrength: -10,
    skinProtect: 96,
  }),
  preset('japan_magazine', '日杂风', 'japanese', '轻复古、纸感、低饱和', {
    brightness: 102,
    contrast: 92,
    saturation: 82,
    sepia: 6,
    fade: 18,
    lutStyle: 'film_matte',
    lutIntensity: 56,
    curveStrength: -12,
    grain: 8,
    skinProtect: 88,
  }),
  preset('anime_clear', '动漫感', 'japanese', '明亮、干净、色彩轻快', {
    brightness: 108,
    contrast: 108,
    saturation: 116,
    temperature: -6,
    lutStyle: 'japan_clear',
    lutIntensity: 64,
    curveStrength: 8,
    skinProtect: 78,
  }),

  preset('premium_oat', '燕麦', 'social', '米白、低对比、高级日常', {
    brightness: 104,
    contrast: 90,
    saturation: 82,
    sepia: 2,
    fade: 14,
    lutStyle: 'xiaohongshu_oat',
    lutIntensity: 56,
    curveStrength: -12,
    skinProtect: 96,
  }),
  preset('cream_ins', '奶油感', 'social', '柔亮奶油色社交风', {
    brightness: 106,
    contrast: 92,
    saturation: 88,
    fade: 12,
    highlightWarm: 6,
    lutStyle: 'korean_cream',
    lutIntensity: 46,
    curveStrength: -10,
    skinProtect: 98,
  }),
  preset('minimal_gray', '极简灰', 'social', '低饱和、干净、偏建筑感', {
    brightness: 100,
    contrast: 96,
    saturation: 68,
    temperature: -4,
    fade: 6,
    lutStyle: 'urban_steel',
    lutIntensity: 30,
    curveStrength: 4,
  }),
  preset('french_cream', '法式奶油', 'social', '柔和暖光和低饱和', {
    brightness: 104,
    contrast: 92,
    saturation: 84,
    sepia: 4,
    temperature: 6,
    fade: 12,
    lutStyle: 'xiaohongshu_oat',
    lutIntensity: 48,
    curveStrength: -10,
    skinProtect: 96,
  }),
  preset('blogger_clear', '清透博主风', 'social', '明亮、清透、轻微增色', {
    brightness: 106,
    contrast: 104,
    saturation: 102,
    temperature: -2,
    lutStyle: 'clean',
    lutIntensity: 28,
    curveStrength: 4,
    skinProtect: 92,
  }),

  preset('canon_portrait', 'Canon 人像', 'camera', '柔和肤色、暖调人像', cameraParams('canon_portrait', {
    brightness: 103,
    contrast: 100,
    saturation: 95,
    exposure: 2,
    highlights: -6,
    shadows: 5,
    skinSmooth: 10,
    skinWarmth: 4,
    lutStyle: 'kodak_portra',
    lutIntensity: 26,
    profileIntensity: 52,
    skinProtect: 98,
  })),
  preset('leica_classic', 'Leica 经典', 'camera', '微暖、高微反差、街拍感', cameraParams('leica_classic', {
    brightness: 100,
    contrast: 110,
    saturation: 94,
    blackPoint: 6,
    vibrance: 6,
    clarity: 10,
    lutStyle: 'film_matte',
    lutIntensity: 30,
    curveStrength: 8,
    grain: 5,
    profileIntensity: 56,
  })),
  preset('hasselblad_natural', '哈苏自然', 'camera', '自然色彩和柔和层次', cameraParams('hasselblad_natural', {
    brightness: 101,
    contrast: 100,
    saturation: 96,
    highlights: -8,
    shadows: 6,
    vibrance: 4,
    lutStyle: 'clean',
    lutIntensity: 18,
    curveStrength: 0,
    profileIntensity: 54,
    skinProtect: 96,
  })),
  preset('ricoh_gr_street', 'Ricoh GR', 'camera', '街拍、硬朗、微冷灰阶', cameraParams('ricoh_gr', {
    brightness: 99,
    contrast: 114,
    saturation: 84,
    temperature: -4,
    blackPoint: 8,
    clarity: 12,
    grain: 8,
    lutStyle: 'urban_steel',
    lutIntensity: 30,
    curveStrength: 10,
    profileIntensity: 54,
  })),
  preset('sony_clean', 'Sony 清晰', 'camera', '干净锐利、冷白通透', cameraParams('sony_clean', {
    brightness: 103,
    contrast: 106,
    saturation: 100,
    temperature: -4,
    highlights: -4,
    clarity: 10,
    vibrance: 6,
    lutStyle: 'clean',
    lutIntensity: 22,
    curveStrength: 6,
    profileIntensity: 46,
  })),
  preset('iphone_vivid', 'iPhone 鲜明', 'camera', '明亮、鲜明、社交友好', cameraParams('iphone_vivid', {
    brightness: 103,
    contrast: 108,
    saturation: 104,
    exposure: 2,
    highlights: -6,
    shadows: 6,
    vibrance: 8,
    lutStyle: 'clean',
    lutIntensity: 20,
    curveStrength: 6,
    profileIntensity: 48,
    skinProtect: 92,
  })),
  preset('nikon_landscape', 'Nikon 风景', 'camera', '蓝绿更扎实的风景色彩', cameraParams('nikon_landscape', {
    brightness: 100,
    contrast: 110,
    saturation: 106,
    temperature: -3,
    highlights: -4,
    shadows: 4,
    vibrance: 10,
    clarity: 10,
    lutStyle: 'nature',
    lutIntensity: 30,
    curveStrength: 8,
    profileIntensity: 52,
  })),

  preset('mono_classic', '黑白经典', 'mono', '标准黑白', {
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 24,
  }),
  preset('mono_high_contrast', '高对比黑白', 'mono', '更强的明暗关系', {
    brightness: 98,
    contrast: 132,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 58,
    curveStrength: 24,
    grain: 8,
  }),
  preset('mono_soft', '柔和黑白', 'mono', '低对比、更安静', {
    brightness: 104,
    contrast: 88,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 20,
    curveStrength: -12,
  }),
  preset('graphite', '石墨', 'mono', '偏硬朗的灰阶质感', {
    brightness: 96,
    contrast: 126,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 42,
    curveStrength: 16,
  }),
  preset('shadow_mono', '阴影', 'mono', '压暗部的黑白氛围', {
    brightness: 88,
    contrast: 132,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 56,
    curveStrength: 18,
  }),
  preset('light_shadow_mono', '光影黑白', 'mono', '适合建筑和街头', {
    brightness: 100,
    contrast: 138,
    saturation: 0,
    grayscale: 100,
    lutStyle: 'noir',
    lutIntensity: 64,
    curveStrength: 26,
  }),

  preset('dream', '梦境', 'dream', '柔和、微亮、轻微朦胧', {
    brightness: 108,
    contrast: 92,
    saturation: 106,
    blur: 0.45,
    fade: 14,
    tint: 6,
    lutStyle: 'dream',
    lutIntensity: 68,
    curveStrength: -12,
    skinProtect: 90,
  }),
  preset('pearl_glow', '珍珠光', 'dream', '柔亮偏白的光感', {
    brightness: 112,
    contrast: 90,
    saturation: 96,
    blur: 0.25,
    fade: 18,
    highlightWarm: 8,
    lutStyle: 'dream',
    lutIntensity: 72,
    curveStrength: -16,
    skinProtect: 92,
  }),
  preset('morning_fog', '晨雾', 'dream', '低对比雾感', {
    brightness: 107,
    contrast: 86,
    saturation: 88,
    blur: 0.35,
    temperature: -4,
    fade: 20,
    lutStyle: 'dream',
    lutIntensity: 66,
    curveStrength: -16,
    skinProtect: 92,
  }),
  preset('aurora', '极光', 'dream', '冷艳、轻微偏梦幻', {
    brightness: 102,
    contrast: 112,
    saturation: 116,
    temperature: -10,
    tint: 12,
    shadowCool: 16,
    lutStyle: 'dream',
    lutIntensity: 56,
    curveStrength: 8,
  }),
  preset('stardust', '星尘', 'dream', '暗部保留、色彩更轻盈', {
    brightness: 98,
    contrast: 112,
    saturation: 116,
    sepia: 4,
    shadowCool: 10,
    highlightWarm: 10,
    vignette: 12,
    lutStyle: 'dream',
    lutIntensity: 48,
    curveStrength: 6,
    grain: 6,
  }),
  preset('moon_dream', '月光梦', 'dream', '月光感冷调', {
    brightness: 100,
    contrast: 96,
    saturation: 82,
    temperature: -16,
    shadowCool: 18,
    fade: 10,
    lutStyle: 'night',
    lutIntensity: 42,
    curveStrength: -8,
  }),

  preset('forest', '森林', 'nature', '加强绿色与自然层次', {
    brightness: 100,
    contrast: 110,
    saturation: 112,
    temperature: -4,
    shadowCool: 6,
    lutStyle: 'nature',
    lutIntensity: 46,
    curveStrength: 8,
  }),
  preset('sea_breeze', '海风', 'nature', '偏蓝、通透、轻盈', {
    brightness: 106,
    contrast: 104,
    saturation: 110,
    temperature: -10,
    shadowCool: 8,
    lutStyle: 'nature',
    lutIntensity: 38,
    curveStrength: -4,
  }),
  preset('sunset', '日落', 'nature', '暖色更饱满', {
    brightness: 102,
    contrast: 106,
    saturation: 110,
    sepia: 6,
    temperature: 12,
    highlightWarm: 20,
    lutStyle: 'film_gold',
    lutIntensity: 48,
    curveStrength: 8,
    skinProtect: 82,
  }),
  preset('golden_hour', '黄金时刻', 'nature', '更柔和的金色光线', {
    brightness: 104,
    contrast: 102,
    saturation: 108,
    sepia: 10,
    temperature: 16,
    highlightWarm: 24,
    fade: 5,
    lutStyle: 'film_gold',
    lutIntensity: 64,
    curveStrength: 4,
    skinProtect: 82,
  }),
  preset('snow', '雪境', 'nature', '提高白色洁净感', {
    brightness: 112,
    contrast: 102,
    saturation: 84,
    temperature: -12,
    fade: 6,
    lutStyle: 'clean',
    lutIntensity: 30,
    curveStrength: -6,
  }),
  preset('clear_sky', '晴空', 'nature', '蓝天更干净', {
    brightness: 106,
    contrast: 108,
    saturation: 114,
    temperature: -8,
    shadowCool: 6,
    lutStyle: 'clean',
    lutIntensity: 34,
    curveStrength: 8,
  }),

  preset('city_lights', '城市之光', 'night', '夜景更亮，保留色彩', nightParams({
    brightness: 104,
    contrast: 118,
    saturation: 116,
    shadowCool: 12,
    vignette: 10,
    lutStyle: 'night',
    lutIntensity: 50,
    curveStrength: 12,
  })),
  preset('neon', '霓虹', 'night', '强化霓虹色彩', nightParams({
    brightness: 98,
    contrast: 120,
    saturation: 122,
    tint: 12,
    shadowCool: 18,
    vignette: 16,
    lutStyle: 'neon',
    lutIntensity: 74,
    curveStrength: 18,
  })),
  preset('midnight', '午夜', 'night', '压暗、低饱和、冷静', {
    brightness: 86,
    contrast: 120,
    saturation: 78,
    temperature: -16,
    shadowCool: 22,
    vignette: 28,
    lutStyle: 'night',
    lutIntensity: 66,
    curveStrength: 16,
  }),
  preset('blue_hour', '蓝调时刻', 'night', '日落后冷蓝氛围', {
    brightness: 96,
    contrast: 112,
    saturation: 92,
    temperature: -18,
    shadowCool: 18,
    fade: 6,
    lutStyle: 'night',
    lutIntensity: 52,
    curveStrength: 4,
  }),
  preset('tokyo_night', '东京夜色', 'night', '城市夜色与霓虹平衡', {
    brightness: 96,
    contrast: 118,
    saturation: 116,
    temperature: -8,
    tint: 8,
    shadowCool: 16,
    vignette: 14,
    lutStyle: 'neon',
    lutIntensity: 58,
    curveStrength: 12,
  }),
  preset('rain_window', '雨窗情绪', 'night', '低对比、冷调、湿润感', {
    brightness: 94,
    contrast: 98,
    saturation: 86,
    blur: 0.2,
    temperature: -12,
    shadowCool: 18,
    fade: 12,
    lutStyle: 'night',
    lutIntensity: 44,
    curveStrength: -6,
  }),

  preset('cyberpunk', '赛博朋克', 'future', '高对比、霓虹、未来感', {
    brightness: 96,
    contrast: 122,
    saturation: 120,
    temperature: -12,
    tint: 18,
    shadowCool: 24,
    vignette: 18,
    lutStyle: 'cyber',
    lutIntensity: 74,
    curveStrength: 18,
  }),
  preset('future_blue', '未来蓝', 'future', '偏蓝科技感', {
    brightness: 98,
    contrast: 120,
    saturation: 112,
    temperature: -22,
    shadowCool: 24,
    lutStyle: 'cyber',
    lutIntensity: 62,
    curveStrength: 12,
  }),
  preset('ai_core', 'AI核心', 'future', '冷光、干净、硬朗', {
    brightness: 100,
    contrast: 120,
    saturation: 108,
    temperature: -14,
    shadowCool: 18,
    vignette: 8,
    lutStyle: 'cyber',
    lutIntensity: 48,
    curveStrength: 14,
  }),
  preset('hologram', '全息', 'future', '偏青紫的全息光感', {
    brightness: 104,
    contrast: 112,
    saturation: 116,
    temperature: -8,
    tint: 14,
    fade: 8,
    shadowCool: 12,
    lutStyle: 'cyber',
    lutIntensity: 52,
    curveStrength: -2,
  }),
  preset('data_stream', '数据流', 'future', '高对比电子屏幕感', {
    brightness: 98,
    contrast: 124,
    saturation: 112,
    temperature: -18,
    shadowCool: 20,
    vignette: 12,
    lutStyle: 'cyber',
    lutIntensity: 58,
    curveStrength: 18,
  }),
  preset('spectrum', '光谱', 'future', '彩色光谱增强', {
    brightness: 102,
    contrast: 114,
    saturation: 122,
    tint: 8,
    highlightWarm: 8,
    lutStyle: 'neon',
    lutIntensity: 54,
    curveStrength: 10,
  }),
]

/** 兼容旧版预设 id。旧风格不再展示，只映射到新的可用预设。 */
const PRESET_ID_ALIASES = {
  pro_teal_orange: 'teal_orange',
  teal_orange_cinema: 'teal_orange',
  pro_noir: 'midnight_theater',
  noir_crush: 'midnight_theater',
  pro_golden_hour: 'golden_hour',
  pro_moody_blue: 'blue_hour',
  moody_blue: 'blue_hour',
  pro_analog_fade: 'retro_film',
  analog_fade: 'retro_film',
  pro_cyber_neon: 'cyberpunk',
  cyber_neon: 'cyberpunk',
  kodak_portrait: 'kodak_portra',
  korean_clear: 'k_drama',
  milk_skin: 'cream_skin',
  seoul_soft: 'seoul',
  japanese_clear: 'tokyo',
  cherry_blossom: 'sakura',
  oat: 'premium_oat',
  cream: 'cream_ins',
  canon: 'canon_portrait',
  leica: 'leica_classic',
  hasselblad: 'hasselblad_natural',
  ricoh: 'ricoh_gr_street',
  sony: 'sony_clean',
  iphone: 'iphone_vivid',
  nikon: 'nikon_landscape',
  cinema: 'cinematic',
  cool: 'cool_tone',
  warm: 'warm_sun',
  sharp: 'hd_clear',
  blur: 'soft_focus',
  invert: 'none',
  clean_natural: 'natural',
  soft_warm: 'warm_sun',
  cool_clear: 'cool_tone',
  soft_film: 'matte_film',
  balanced_dark: 'midnight',
  slightly_crisp: 'hd_clear',
  grayscale: 'mono_classic',
  sepia: 'old_photo',
  vintage: 'retro_film',
}

export function normalizePresetId(id) {
  if (!id) return id
  return PRESET_ID_ALIASES[id] || id
}

export function getFilterPresetById(id) {
  const resolved = normalizePresetId(id)
  return FILTER_PRESETS.find((p) => p.id === resolved) || null
}
