import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'
import {
  subjectPath, opaquePng, squarePng, alphaBounds, png, hash, setup, stageState, readyCard, bytes, exportCard, picture, openEditor, closeEditor, rawSubject, fourLayers, noAI, artifact, pixelsEqual, calibrationPixels
} from './helpers/holoTemplateHarness.js'

test.use({ video: 'off' })

test.describe('Holo user template parity', () => {
  test('the real same-template upload reproduces the gallery pixels and its four physical layers', async ({ page }, testInfo) => {
    test.setTimeout(45_000)
    const calls = await setup(page, { signedIn: false })
    const subject = await readFile(subjectPath)
    await page.goto('/holo-card/sample', { waitUntil: 'domcontentloaded' })
    await readyCard(page)
    const galleryState = await stageState(page)
    fourLayers(galleryState)
    expect(galleryState.pose).toEqual({ x: -.3, y: .045, flip: 0 })
    expect(galleryState.finishWeights.gold).toBe(1)
    const gallery = await exportCard(page, '保存画面')
    await page.getByRole('link', { name: '制作同款', exact: true }).click()
    await expect(page).toHaveURL(/\/holo-card(?:\?|$)/)
    await picture(page, 'same-gallery-subject.png', subject)
    await readyCard(page)
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
    const uploadedState = await stageState(page)
    fourLayers(uploadedState)
    expect(uploadedState.pose).toEqual(galleryState.pose)
    expect(uploadedState.framing.strategy).toBe('native')
    expect(uploadedState.framing.uvScale).toEqual({ x: 1, y: 1 })
    expect(await rawSubject(page)).toEqual(subject)
    await closeEditor(page)
    const uploaded = await exportCard(page, '导出 PNG')
    const difference = await pixelsEqual(page, gallery, uploaded)
    expect(difference.changedPixels).toBe(0)
    expect(difference.maxDelta).toBe(0)
    await artifact(testInfo, 'gallery-reference.png', gallery)
    await artifact(testInfo, 'user-template-identical.png', uploaded)
    await artifact(testInfo, 'template-pixel-parity.json', JSON.stringify({ difference, galleryState, uploadedState,
      originalSubjectHash: hash(subject), galleryPngHash: hash(gallery), uploadedPngHash: hash(uploaded) }, null, 2), 'application/json')
    noAI(calls)
  })

  test('an opaque image previews the template and only explicit generation plus adoption completes the four layers', async ({ page }, testInfo) => {
    const calls = await setup(page)
    await page.goto('/holo-card?template=astral', { waitUntil: 'domcontentloaded' })
    await picture(page, 'ordinary-picture.png', opaquePng)
    await readyCard(page)
    await expect(page.getByRole('heading', { name: '再分离主体，就有示例层次', exact: true })).toBeVisible()
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'original')
    expect((await stageState(page)).framing.strategy).toBe('contain')
    noAI(calls)
    await page.getByRole('button', { name: '开始生成同款', exact: true }).click()
    const confirmation = page.getByRole('alertdialog', { name: '确认生成透明主体？', exact: true })
    await expect(confirmation).toContainText('12 积分')
    expect(calls.quotes).toHaveLength(1)
    expect(calls.quotes[0]).toMatchObject({ type: 't2i', inputKeys: [], count: 1, params: {
      strictAlphaOutput: true, inputFidelity: 'high', quality: 'high', transparentBackground: true, autoBackgroundRemovalEnabled: false,
    } })
    expect(calls.uploads).toHaveLength(0)
    expect(calls.created).toHaveLength(0)
    await confirmation.getByRole('button', { name: '确认生成', exact: true }).click()
    await expect(page.getByAltText('待验收透明主体')).toBeVisible()
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'original')
    await expect(page.getByRole('button', { name: '下载原始透明 PNG', exact: true })).toHaveCount(0)
    expect(calls.uploads).toHaveLength(1)
    expect(calls.created).toHaveLength(1)
    expect(calls.created[0]).toMatchObject({ expectedUnitPriceCents: 12, count: 1, params: {
      strictAlphaOutput: true, inputFidelity: 'high', quality: 'high', autoBackgroundRemovalEnabled: false,
    } })
    expect(calls.uploads[0].postDataBuffer().includes(opaquePng)).toBe(true)
    await page.getByRole('button', { name: '采用此图层', exact: true }).click()
    await readyCard(page)
    await expect(page.getByRole('heading', { name: '你的同款闪卡已完成', exact: true })).toBeVisible()
    const result = await stageState(page)
    fourLayers(result)
    expect(result.sourceDimensions.subject).toEqual({ width: 1024, height: 1024 })
    expect(result.framing.strategy).toBe('auto')
    expect(await rawSubject(page)).toEqual(squarePng)
    expect(calls.quotes).toHaveLength(1)
    expect(calls.created).toHaveLength(1)
    expect(calls.removals).toHaveLength(0)
    expect(calls.errors).toEqual([])
    await artifact(testInfo, 'adopted-template-layers.json', JSON.stringify(result, null, 2), 'application/json')
  })

  test('square transparent padding preserves alpha-1 bounds and renders an undistorted complete subject', async ({ page }, testInfo) => {
    const calls = await setup(page, { signedIn: false })
    await page.goto('/holo-card', { waitUntil: 'domcontentloaded' })
    await picture(page, 'square-padded-subject.png', squarePng)
    const stage = await readyCard(page)
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
    const fitted = await stageState(page)
    fourLayers(fitted)
    expect(fitted.framing.strategy).toBe('auto')
    expect(fitted.framing.sourceBounds).toEqual(alphaBounds)
    expect(fitted.framing.displayBounds.x).toBeGreaterThan(0)
    expect(fitted.framing.displayBounds.y).toBeGreaterThan(0)
    expect(fitted.framing.displayBounds.x + fitted.framing.displayBounds.width).toBeLessThan(1)
    expect(fitted.framing.displayBounds.y + fitted.framing.displayBounds.height).toBeLessThan(1)
    expect(await rawSubject(page)).toEqual(squarePng)
    await closeEditor(page)
    await page.getByRole('button', { name: '原画', exact: true }).click()
    await stage.press('Home')
    expect((await stageState(page)).pose).toEqual({ x: 0, y: 0, flip: 0 })
    const exported = await exportCard(page, '导出 PNG')
    const pixels = await calibrationPixels(page, exported)
    const circle = pixels.circle
    expect(circle.count).toBeGreaterThan(1000)
    expect(Math.abs((circle.right - circle.left + 1) / (circle.bottom - circle.top + 1) - 1)).toBeLessThan(.025)
    for (const name of ['red', 'green', 'blue', 'cyan']) {
      const marker = pixels[name]
      expect(marker.count, name).toBeGreaterThan(20)
      expect(marker.left, name).toBeGreaterThan(8)
      expect(marker.top, name).toBeGreaterThan(8)
      expect(marker.right, name).toBeLessThan(1592)
      expect(marker.bottom, name).toBeLessThan(2392)
    }
    expect(pixels.red.right).toBeLessThan(circle.left)
    expect(pixels.green.left).toBeGreaterThan(circle.right)
    expect(pixels.blue.bottom).toBeLessThan(circle.top)
    expect(pixels.cyan.top).toBeGreaterThan(circle.bottom)
    await artifact(testInfo, 'square-subject-source.png', squarePng)
    await artifact(testInfo, 'square-subject-template.png', exported)
    await artifact(testInfo, 'square-subject-framing.json', JSON.stringify({ fitted, pixels, originalHash: hash(squarePng) }, null, 2), 'application/json')
    noAI(calls)
  })

  test('explicit transparent imports still reject empty, fake-alpha, and low-resolution images without replacing the subject', async ({ page }) => {
    const calls = await setup(page, { signedIn: false }), subject = await readFile(subjectPath)
    await page.goto('/holo-card', { waitUntil: 'domcontentloaded' })
    await picture(page, 'verified-local-subject.png', subject)
    await readyCard(page)
    await openEditor(page, '图层')
    for (const [name, buffer, error] of [
      ['empty.png', png('empty'), '图片接近全透明'],
      ['painted-checkerboard.png', png('checker'), '未检测到足够的真实透明区域'],
      ['small.png', png('calibration', 512, 512), '透明主体短边至少需要 1024 像素'],
    ]) {
      const choosing = page.waitForEvent('filechooser')
      await page.getByRole('button', { name: '导入透明 PNG', exact: true }).click()
      await (await choosing).setFiles({ name, mimeType: 'image/png', buffer })
      await expect(page.locator('.holo-error')).toContainText(error)
      await expect(page.getByRole('button', { name: '采用此图层', exact: true })).toHaveCount(0)
      await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
      await expect(page.getByRole('button', { name: '导出 PNG', exact: true })).toBeEnabled()
      await page.getByRole('button', { name: '关闭错误', exact: true }).click()
    }
    fourLayers(await stageState(page))
    expect(await rawSubject(page)).toEqual(subject)
    noAI(calls)
  })

  test('custom layers validate registration and consecutive subject replacements rebuild the final template', async ({ page }, testInfo) => {
    test.setTimeout(60_000)
    const calls = await setup(page, { signedIn: false }), subject = await readFile(subjectPath)
    await page.goto('/holo-card', { waitUntil: 'domcontentloaded' })
    await picture(page, 'initial-portrait.png', subject)
    await readyCard(page)
    const original = await exportCard(page, '导出 PNG')
    await openEditor(page, '图层')
    const backgroundChoice = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: /^示例星轨背景/ }).click()
    await (await backgroundChoice).setFiles({ name: 'custom-landscape.png', mimeType: 'image/png', buffer: png('opaque', 1600, 900) })
    await readyCard(page)
    expect((await stageState(page)).sourceDimensions.background).toEqual({ width: 1600, height: 900 })
    const custom = await exportCard(page, '导出 PNG')
    expect((await pixelsEqual(page, original, custom)).changedPixels).toBeGreaterThan(10000)
    await page.locator('summary').filter({ hasText: '轮廓线稿' }).click()
    const mismatched = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: /^导入线稿/ }).click()
    await (await mismatched).setFiles({ name: 'wrong-canvas.png', mimeType: 'image/png', buffer: png('lineart') })
    await expect(page.locator('.holo-error')).toContainText('线稿画布尺寸必须与透明主体完全一致')
    await expect(page.getByRole('tab', { name: '线稿', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '关闭错误', exact: true }).click()
    const matched = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: /^导入线稿/ }).click()
    await (await matched).setFiles({ name: 'matched-lines.png', mimeType: 'image/png', buffer: png('lineart', 1024, 1536) })
    await readyCard(page)
    expect((await stageState(page)).sourceDimensions.lineart).toEqual({ width: 1024, height: 1536 })
    // Replace as soon as each file has been accepted, without waiting for the
    // first image's renderer work; the final file must win the async rebuild.
    await picture(page, 'intermediate-square.png', squarePng)
    await picture(page, 'final-portrait.png', subject)
    await readyCard(page)
    await expect.poll(async () => (await stageState(page)).sourceDimensions.subject).toEqual({ width: 1024, height: 1536 })
    const final = await stageState(page)
    expect(final.sourceDimensions).not.toHaveProperty('lineart')
    expect(final.framing.strategy).toBe('native')
    await expect(page.getByRole('tab', { name: '线稿', exact: true })).toHaveCount(0)
    expect(await rawSubject(page)).toEqual(subject)
    await page.getByRole('button', { name: '恢复示例星轨背景', exact: true }).click()
    await readyCard(page)
    fourLayers(await stageState(page))
    await openEditor(page, '设计')
    await page.getByRole('button', { name: '原图闪卡', exact: true }).click()
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'original')
    await closeEditor(page)
    await page.getByRole('button', { name: '返回同款预览', exact: true }).click()
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
    await readyCard(page)
    await openEditor(page, '设计')
    await page.getByRole('button', { name: '原图闪卡', exact: true }).click()
    await page.getByRole('button', { name: '重新套用示例版式', exact: true }).click()
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
    await readyCard(page)
    fourLayers(await stageState(page))
    expect((await stageState(page)).framing.strategy).toBe('native')
    expect(await rawSubject(page)).toEqual(subject)
    await artifact(testInfo, 'custom-background-template.png', custom)
    await artifact(testInfo, 'final-template-rebuild.json', JSON.stringify(await stageState(page), null, 2), 'application/json')
    noAI(calls)
  })

  test('mobile same-template steps lead to a usable pure stage and the primary save action', async ({ page }, testInfo) => {
    test.setTimeout(60_000)
    const viewport = { width: 390, height: 844 }, calls = await setup(page, { viewport })
    await page.goto('/holo-card/sample', { waitUntil: 'domcontentloaded' })
    const same = page.getByRole('link', { name: '制作同款', exact: true })
    await expect(same).toBeInViewport()
    await same.click()
    await expect(page.getByRole('button', { name: '选图制作同款', exact: true })).toBeInViewport()
    await picture(page, 'mobile-portrait.png', await readFile(subjectPath))
    const stage = await readyCard(page)
    await expect(page.getByRole('heading', { name: '你的同款闪卡已完成', exact: true })).toBeVisible()
    const guide = page.getByRole('complementary', { name: '制卡步骤', exact: true })
    await expect(guide).toContainText('同款完成')
    await expect(page.getByRole('button', { name: '导出同款闪卡', exact: true })).toBeInViewport()
    const exported = await exportCard(page, '导出同款闪卡')
    await page.getByRole('button', { name: '隐藏工具', exact: true }).click()
    await expect(guide).toBeHidden()
    await expect(page.getByRole('navigation', { name: '创作工具', exact: true })).toBeHidden()
    await expect(stage).toBeVisible()
    const bounds = await stage.boundingBox()
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.y).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(viewport.width)
    expect(bounds.y + bounds.height).toBeLessThanOrEqual(viewport.height)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width)
    fourLayers(await stageState(page))
    await artifact(testInfo, 'mobile-pure-template.png', await page.screenshot())
    await artifact(testInfo, 'mobile-template-export.png', exported)
    await page.getByRole('button', { name: '显示工具', exact: true }).click()
    await expect(page.getByRole('button', { name: '导出同款闪卡', exact: true })).toBeInViewport()
    noAI(calls)

    await picture(page, 'mobile-photo-needing-subject.png', opaquePng)
    await readyCard(page)
    const generate = page.getByRole('button', { name: '开始生成同款', exact: true })
    await expect(generate).toBeInViewport()
    await generate.click()
    const confirmation = page.getByRole('alertdialog', { name: '确认生成透明主体？', exact: true })
    await expect(confirmation).toContainText('12 积分')
    expect(calls.uploads).toHaveLength(0)
    expect(calls.created).toHaveLength(0)
    const confirmButton = confirmation.getByRole('button', { name: '确认生成', exact: true })
    await expect(confirmButton).toBeInViewport()
    await confirmButton.click()
    const candidate = page.getByAltText('待验收透明主体')
    await expect(candidate).toBeVisible()
    const inspection = await page.getByLabel('原尺寸图层检查', { exact: true }).boundingBox()
    expect(inspection.width).toBeGreaterThanOrEqual(300)
    expect(inspection.x).toBeGreaterThanOrEqual(0)
    expect(inspection.x + inspection.width).toBeLessThanOrEqual(viewport.width)
    const image = await candidate.boundingBox()
    expect(image.width).toBeGreaterThanOrEqual(280)
    const adopt = page.getByRole('button', { name: '采用此图层', exact: true })
    await expect(adopt).toBeInViewport()
    const adoptionBounds = await adopt.boundingBox()
    expect(adoptionBounds.x).toBeGreaterThanOrEqual(0)
    expect(adoptionBounds.x + adoptionBounds.width).toBeLessThanOrEqual(viewport.width)
    await artifact(testInfo, 'mobile-template-inspection.png', await page.screenshot())
    await adopt.click()
    await readyCard(page)
    await expect(page.locator('[data-card-template="astral"]')).toHaveAttribute('data-holo-mode', 'layered')
    fourLayers(await stageState(page))
    await expect(page.getByRole('button', { name: '导出同款闪卡', exact: true })).toBeEnabled()
    expect(calls.quotes).toHaveLength(1)
    expect(calls.uploads).toHaveLength(1)
    expect(calls.created).toHaveLength(1)
    expect(calls.created[0].expectedUnitPriceCents).toBe(12)
    expect(calls.created[0].params.strictAlphaOutput).toBe(true)
    expect(calls.removals).toHaveLength(0)
    expect(calls.errors).toEqual([])
  })
})
