package main

const consoleHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>支付测试控制台</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#25282d;font:14px/1.6 system-ui,"PingFang SC",sans-serif}main{max-width:1280px;margin:auto;padding:28px 32px}header{display:flex;align-items:center;gap:14px;border-bottom:1px solid #dce2e6;padding-bottom:20px}header img{width:44px;height:44px;object-fit:contain}h1{font-size:24px;margin:0}header small{margin-left:auto;padding:5px 10px;border-radius:4px;color:#22674c;background:#e4f3ea}section{padding:24px 0;border-bottom:1px solid #dce2e6}h2{font-size:16px;margin:0 0 12px}.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}button,select{font:inherit;min-height:34px;border:1px solid #d4dce1;border-radius:5px;background:white;color:#313a45;padding:5px 12px;cursor:pointer}button:hover{background:#eef3f5}button.primary{background:#315a80;color:white;border-color:#315a80}button:disabled{opacity:.5;cursor:wait}button:focus-visible,select:focus-visible{outline:2px solid #5286ab;outline-offset:3px}.accounts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.account{padding:16px;border:1px solid #dce2e6;border-radius:6px;background:white;min-width:0}.account h3{font-size:14px;margin:0}.account p{margin:4px 0 10px;color:#65717e;font-size:12px;overflow-wrap:anywhere}.account strong{display:block;margin:8px 0;color:#285c57;font-size:20px}.account form{display:inline-block;margin:0 6px 0 0}.meta{font-size:12px;color:#6d7782;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;background:white;table-layout:fixed}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #e7ebee;vertical-align:top;overflow-wrap:anywhere}th{font-size:12px;color:#6d7782;background:#f0f3f5}td{font-size:12px}td button{font-size:11px;min-height:28px;padding:3px 7px;margin:0 4px 4px 0}td code{font-size:11px}tr.selected td{background:#edf7f3}.controls{display:flex;gap:8px;flex-wrap:wrap}.result{min-height:36px;white-space:pre-wrap;background:#eaf0f5;color:#345675;padding:12px;border-radius:5px;margin-top:14px}.result.error{background:#fceeee;color:#9a3e3e}a{color:#315a80}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;margin:8px 0}#empty{padding:22px;color:#78828b;text-align:center;background:white}summary{cursor:pointer;color:#65717e}
.consume{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.consume input{width:80px;min-height:34px;padding:5px 8px;border:1px solid #d4dce1;border-radius:5px;font:inherit}.consume button{font-size:12px}.consume input:focus-visible{outline:2px solid #5286ab;outline-offset:3px}@media(max-width:760px){main{padding:18px 16px}.accounts{grid-template-columns:1fr}header{flex-wrap:wrap}}
.scenario-list{display:grid;gap:12px}.scenario{background:white;border-radius:8px;padding:16px;min-width:0}.scenario h3{margin:0;font-size:14px}.scenario p{margin:6px 0 12px}.scenario .row button{margin-left:auto}.scenario-status{font-size:12px;padding:2px 8px;background:#eef2f6;border-radius:20px}.scenario-status.passed,.step-pass{color:#22674c}.scenario-status.failed,.step-fail{color:#a53737}.scenario table{margin-top:12px}.scenario-error{color:#a53737}.scenario th:first-child{width:40%}.scenario th:last-child{width:12%}#scenario-feedback{min-height:22px;margin:6px 0}.scenario time{display:block;margin-top:8px}
</style></head><body><main>
<header><img src="/usage-plan/reward-coin.webp" alt=""><h1>支付测试控制台</h1><small>隔离环境 · 不真实扣款</small></header>
<section><div class="row"><label for="mode">下一次建单</label><select id="mode"><option value="normal">正常建单</option><option value="ambiguous">渠道已建单，但返回 504</option><option value="not_created">渠道未建单，并返回 504</option></select><button class="primary" id="set-mode">应用模式</button><button id="refresh">刷新状态</button><span id="mode-state" class="meta"></span></div>
<div id="result" class="result" role="status">就绪</div></section>
<section><h2>测试账号</h2><div id="accounts" class="accounts"></div></section>
<section aria-labelledby="scenario-title"><div class="row"><h2 id="scenario-title">调价与并发联调测试</h2><button id="scenario-stop" hidden>停止测试</button><button id="scenario-refresh">刷新测试结果</button></div><p class="meta">使用独立临时数据，不修改当前手工测试订单和余额。模型响应由本地模拟服务提供，建单、计费及并发控制走正式代码；测试结束自动清理临时数据。</p><div id="scenario-feedback" class="meta" role="status" aria-live="polite"></div><div id="scenario-list" class="scenario-list"></div></section>
<section><h2>补发与对账</h2><div class="row"><button data-action="catchup">执行一次积分补发</button><button data-action="advance">模拟推进一天并发放</button><button data-action="bulk">准备 550 笔历史订单</button><button data-action="reconcile">运行一批对账</button></div><p id="metrics" class="meta"></p></section>
<section><h2>模拟渠道订单</h2><table><colgroup><col style="width:20%"><col style="width:24%"><col style="width:9%"><col style="width:10%"><col style="width:37%"></colgroup><thead><tr><th>渠道单号</th><th>平台订单号</th><th>金额</th><th>渠道状态</th><th>模拟操作</th></tr></thead><tbody id="gateway-orders"></tbody></table><div id="empty">暂无模拟渠道订单</div></section>
<section><h2>管理端</h2><div id="admin-entry"></div><details><summary>测试管理员凭据</summary><pre id="credentials"></pre></details></section>
<footer class="meta">数据库：{{.DB}} · 仅本机访问</footer>
</main><script>
const key={{.Token}};const result=document.querySelector('#result');const payment=new URLSearchParams(location.search).get('pay');
const $=s=>document.querySelector(s);function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}
const taskView=new URLSearchParams(location.search).get('view')==='tasks';
const taskOrder=['image_multi_user','execution_config','execution_recovery','partial_image','multi_user','model_price','plan_price'];
if(taskView){document.title='任务模拟测试';$('h1').textContent='任务模拟测试';$('header small').textContent='模拟上游 · 不消耗真实模型费用';document.querySelectorAll('main>section').forEach(section=>{section.hidden=section.getAttribute('aria-labelledby')!=='scenario-title'});$('#scenario-title').textContent='一键模拟';$('section[aria-labelledby="scenario-title"]>p').textContent='程序自动创建临时账号、制造排队、修改模型配置并模拟上游成功或失败。你只需点击运行，查看预期值和实测值；不会修改现有测试账号、订单或业务配置。'}
function entry(account,dest,label){const form=node('form');form.method='POST';form.action='/__sandbox/enter';for(const [name,value] of Object.entries({key,account,dest})){const input=node('input');input.type='hidden';input.name=name;input.value=value;form.append(input)}const button=node('button',label);form.append(button);return form}
let scenarioTimer,scenarioPosting=false;
const scenarioLabels={idle:'待测试',running:'运行中',stopping:'正在停止',passed:'通过',failed:'未通过',cancelled:'已停止',interrupted:'已中断',stale:'需要重新验证'};
function renderScenarios(data){const busy=data.items.some(r=>['running','stopping'].includes(r.status));const list=$('#scenario-list');list.replaceChildren();$('#scenario-stop').hidden=!busy;$('#scenario-stop').disabled=scenarioPosting||data.items.some(r=>r.status==='stopping');for(const report of data.items){const card=node('article');card.className='scenario';card.dataset.scenario=report.id;const row=node('div');row.className='row';const badge=node('span',scenarioLabels[report.status]||report.status);badge.className='scenario-status '+report.status;const run=node('button',report.status==='idle'?'运行测试':'重新运行');run.disabled=busy||scenarioPosting||!data.available;run.setAttribute('aria-label','运行'+report.title);run.onclick=()=>scenarioAction('scenario_run',report.id);row.append(node('h3',report.title),badge,run);card.append(row,node('p',report.description));if(report.steps.length){const table=node('table');const head=node('thead');const header=node('tr');for(const title of ['检查项','预期','实测','结果'])header.append(node('th',title));head.append(header);table.append(head);const body=node('tbody');for(const step of report.steps){const tr=node('tr');const status=node('td',step.passed?'通过':'未通过');status.className=step.passed?'step-pass':'step-fail';tr.append(node('td',step.name),node('td',step.expected),node('td',step.actual),status);body.append(tr)}table.append(body);card.append(table)}if(report.error){const error=node('pre',report.error);error.className='scenario-error';card.append(error)}if(report.startedAt){const time=node('time','最近运行：'+new Date(report.startedAt).toLocaleString('zh-CN')+' · 已检查 '+report.steps.length+' 项');time.className='meta';card.append(time)}list.append(card)}$('#scenario-feedback').textContent=!data.available?'测试程序尚未准备，请重启当前测试入口。':busy?'测试进行中，结果自动更新；可继续查看当前手工测试账号。':'每次运行一组测试，下面保留各组最近一次结果。';return busy}
async function refreshScenarios(){clearTimeout(scenarioTimer);try{const response=await fetch('/__sandbox/scenarios');if(!response.ok)throw Error('测试状态加载失败');const data=await response.json();if(taskView)data.items.sort((a,b)=>taskOrder.indexOf(a.id)-taskOrder.indexOf(b.id));if(renderScenarios(data))scenarioTimer=setTimeout(refreshScenarios,1000)}catch(error){$('#scenario-feedback').textContent=error.message+'，正在重试…';scenarioTimer=setTimeout(refreshScenarios,3000)}}
async function scenarioAction(action,id){if(scenarioPosting)return;scenarioPosting=true;$('#scenario-list').querySelectorAll('button').forEach(b=>b.disabled=true);$('#scenario-stop').disabled=true;try{const response=await fetch('/__sandbox/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sandbox-Key':key},body:JSON.stringify({action,id})});const body=await response.json();if(!response.ok)throw Error(body.error||'测试操作失败');scenarioPosting=false;await refreshScenarios()}catch(error){scenarioPosting=false;await refreshScenarios();$('#scenario-feedback').textContent=error.message}}
$('#scenario-stop').onclick=()=>scenarioAction('scenario_stop');$('#scenario-refresh').onclick=refreshScenarios;refreshScenarios();
function consumption(item,box){const sub=item.subscription;const available=item.subscriptionAvailable||0;box.append(node('p','订阅可用 '+available+' · 已使用 '+(item.subscriptionSpent||0)+' · 退订冻结 '+(item.subscriptionHeld||0)));const row=node('div');row.className='consume';const amount=node('input');amount.type='number';amount.min='1';amount.max=String(Math.min(available,1000000));amount.step='1';amount.value='1';amount.setAttribute('aria-label',item.account.name+'模拟使用积分数量');const button=node('button','模拟使用订阅积分');const allowed=!!sub&&sub.BillingVersion===2&&sub.Status==='active'&&available>0;amount.disabled=!allowed;button.disabled=!allowed;button.title=allowed?'只扣除订阅积分，不调用模型':'需要有效且未冻结的订阅积分';button.onclick=async()=>{const points=Number(amount.value);if(!Number.isSafeInteger(points)||points<1||points>available||points>1000000){amount.reportValidity();return}button.disabled=true;amount.disabled=true;try{await action('consume_subscription',{account:item.account.key,subscriptionId:sub.ID,points,id:crypto.randomUUID()})}finally{button.disabled=!allowed;amount.disabled=!allowed}};row.append(amount,button);box.append(row)}
async function action(action,extra={}){result.classList.remove('error');result.textContent='处理中…';try{const r=await fetch('/__sandbox/action',{method:'POST',headers:{'Content-Type':'application/json','X-Sandbox-Key':key},body:JSON.stringify({action,...extra})});const body=await r.json();if(!r.ok)throw Error(body.error||'操作失败');result.textContent=JSON.stringify(body.result,null,2);await refresh()}catch(e){result.classList.add('error');result.textContent=e.message}}
async function refresh(){try{const r=await fetch('/__sandbox/state');const state=await r.json();$('#mode-state').textContent='当前模式：'+({normal:'正常建单',ambiguous:'已建单后丢失响应',not_created:'未建单超时'}[state.mode]||state.mode);$('#mode').value=state.mode;
$('#metrics').textContent='模拟时间：'+new Date(state.clock).toLocaleString('zh-CN')+' · 渠道实际建单请求 '+state.creates+' 次 · 已对账 '+state.checked+' 笔';
const accounts=$('#accounts');accounts.replaceChildren();for(const item of state.accounts){const a=item.account;const box=node('article');box.className='account';box.append(node('h3',a.name),node('p',a.email),node('strong',item.balance.toLocaleString('zh-CN')+' 积分'));const text='订单 '+item.summary.total+' 笔 · 待核实 '+item.summary.uncertain+' 笔'+(item.subscription?' · 当前额度 '+item.subscription.DailyGrantCents:'');box.append(node('p',text));box.append(entry(a.key,'/orders','打开订单'),entry(a.key,'/wallet','打开钱包'),entry(a.key,'/subscriptions','我的订阅'));if(a.key==='demo'||a.key==='subscriptions')box.append(entry(a.key,'/pricing','选择套餐'));consumption(item,box);accounts.append(box)}
const rows=$('#gateway-orders');rows.replaceChildren();$('#empty').hidden=state.gateways.length>0;for(const order of state.gateways){const tr=node('tr');if(order.id===payment)tr.className='selected';const id=node('td');id.append(node('code',order.id));const merchant=node('td');merchant.append(node('code',order.merchantId));tr.append(id,merchant,node('td','¥'+(order.amountCents/100).toFixed(2)),node('td',({0:'未支付',1:'已支付','-1':'已关闭'})[order.state]));const actions=node('td');for(const [name,label] of [['pay','模拟付款并回调'],['paid_only','仅标记已付'],['callback','重放回调'],['expire','模拟过期']]){const b=node('button',label);b.onclick=()=>action(name,{id:order.id});actions.append(b)}tr.append(actions);rows.append(tr)}
$('#credentials').textContent=state.adminEmail+'\n'+state.adminPassword;
}catch(e){result.classList.add('error');result.textContent=e.message}}
$('#admin-entry').append(entry('admin','','打开测试后台'));$('#set-mode').onclick=()=>action('mode',{mode:$('#mode').value});$('#refresh').onclick=refresh;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));refresh();
</script></body></html>`
